require 'plugin.config.fidget'
require 'plugin.config.fugitive'
require 'plugin.config.nvim-tree'
require 'plugin.config.bufferline'
require 'plugin.config.lualine'
require 'plugin.config.gitsigns'
require 'plugin.config.telescope'
require 'plugin.config.nvim-treesitter'
require 'plugin.config.lsp'
require 'plugin.config.cmp'
require 'plugin.config.comment'
require 'plugin.config.toggleterm'
require 'plugin.config.crates'
require 'plugin.config.indent-blankline'
require 'plugin.config.autopairs'
require 'plugin.config.trouble'

